language: java
jdk: openjdk19

script: mvn install -Ddependency-check.skip=true -Djacoco.skip=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jobs:
  include:
    - stage: "Tests & Sonar Scan"
      script: mvn clean verify sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master