language: java
jdk: openjdk19

script: mvn install -Ddependency-check.skip=true -Djacoco.skip=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: mvn test -B
    - stage: "Sonar Scan"
      script: mvn clean verify sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN -Dmaven.test.skip=true

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master